# Generated by Django 2.2.17 on 2020-12-29 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercertification',
            options={'verbose_name': 'User Certification'},
        ),
        migrations.AlterModelOptions(
            name='useremployer',
            options={'verbose_name': 'User Employer'},
        ),
        migrations.AlterModelOptions(
            name='userlicense',
            options={'verbose_name': 'User License'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.AlterModelOptions(
            name='userschool',
            options={'verbose_name': 'User School'},
        ),
        migrations.AlterModelOptions(
            name='usersetting',
            options={'verbose_name': 'User Setting'},
        ),
    ]
