# Generated by Django 2.2.17 on 2020-12-29 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subq',
            options={'verbose_name': 'Sub Q'},
        ),
        migrations.AlterModelOptions(
            name='subqfollower',
            options={'verbose_name': 'Sub Follower'},
        ),
        migrations.RemoveField(
            model_name='subq',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subqfollower',
            name='user',
        ),
        migrations.AddField(
            model_name='subq',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subqfollower',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subqfollower',
            name='is_banned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subqfollower',
            name='subq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to='subq.SubQ'),
        ),
    ]
