# Generated by Django 2.2.17 on 2020-12-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subq', '0002_auto_20201229_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subq',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subqfollower',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
