# Generated by Django 2.2.17 on 2021-01-07 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionwatchers',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='questionwatchers',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
